language: ruby
script: 
- bundle exec rake test_with_coveralls
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - jruby-19mode
matrix:
  allow_failures:
  # until fixed https://github.com/travis-ci/travis-ci/issues/2220
  - rvm: 2.1